/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;


import reference.Interface;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        options();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        l_title = new javax.swing.JLabel();
        btn_start = new javax.swing.JLabel();
        btn_about = new javax.swing.JLabel();
        btn_quit = new javax.swing.JLabel();
        l_66 = new javax.swing.JLabel();
        l_console = new javax.swing.JLabel();
        l_9 = new javax.swing.JLabel();
        l_3 = new javax.swing.JLabel();
        l_007 = new javax.swing.JLabel();
        l_6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        l_rules = new javax.swing.JLabel();
        l_r1 = new javax.swing.JLabel();
        l_r2 = new javax.swing.JLabel();
        l_r3 = new javax.swing.JLabel();
        l_r4 = new javax.swing.JLabel();
        l_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_title.setBackground(new java.awt.Color(255, 255, 255));
        l_title.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        l_title.setForeground(new java.awt.Color(255, 255, 255));
        l_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_title.setText("NUMBER GUESSING GAME !!");
        jPanel2.add(l_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 380, 31));

        btn_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start_button.png"))); // NOI18N
        btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_startMouseClicked(evt);
            }
        });
        jPanel2.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        btn_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about_button.png"))); // NOI18N
        btn_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aboutMouseClicked(evt);
            }
        });
        jPanel2.add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        btn_quit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quit_button.png"))); // NOI18N
        btn_quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_quitMouseClicked(evt);
            }
        });
        jPanel2.add(btn_quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        l_66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/66.png"))); // NOI18N
        jPanel2.add(l_66, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        l_console.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calc.png"))); // NOI18N
        jPanel2.add(l_console, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        l_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.png"))); // NOI18N
        jPanel2.add(l_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));

        l_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        jPanel2.add(l_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        l_007.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/007.png"))); // NOI18N
        jPanel2.add(l_007, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        l_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.png"))); // NOI18N
        jPanel2.add(l_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 830, 10));

        l_rules.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        l_rules.setForeground(new java.awt.Color(255, 255, 255));
        l_rules.setText("Rules:");
        jPanel2.add(l_rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 63, 28));

        l_r1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        l_r1.setForeground(new java.awt.Color(255, 255, 255));
        l_r1.setText("1) The player should enter the number between 1-100. ");
        jPanel2.add(l_r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 30));

        l_r2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        l_r2.setForeground(new java.awt.Color(255, 255, 255));
        l_r2.setText("2) You have only 10 lives(i.e., chances) to guess the correct number.");
        jPanel2.add(l_r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, 28));

        l_r3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        l_r3.setForeground(new java.awt.Color(255, 255, 255));
        l_r3.setText("3) Once you reset the best score, then you cannot retrive the previous best score again. ");
        jPanel2.add(l_r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, 28));

        l_r4.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        l_r4.setForeground(new java.awt.Color(255, 255, 255));
        l_r4.setText("4) Once the NewRadomNumber button is pressed, then you cannot retrive the previous random number.");
        jPanel2.add(l_r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, 28));

        l_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel2.add(l_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 850, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_quitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quitMouseClicked
        Object[] options = {"YES","NO"};
        int x = JOptionPane.showOptionDialog(this, "Are you sure, You want to Quit (yes/no) ?", "MESSAGE", 
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, null);  
        if (x == JOptionPane.YES_NO_OPTION){
           System.exit(0); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_quitMouseClicked

    private void btn_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_startMouseClicked
            NumberGuessGame gg = new NumberGuessGame();
            gg.setVisible(true);
            dispose();
    }//GEN-LAST:event_btn_startMouseClicked

    private void btn_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseClicked
            about ab = new about();
            ab.setVisible(true);  
            dispose();
    }//GEN-LAST:event_btn_aboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_about;
    private javax.swing.JLabel btn_quit;
    private javax.swing.JLabel btn_start;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_007;
    private javax.swing.JLabel l_3;
    private javax.swing.JLabel l_6;
    private javax.swing.JLabel l_66;
    private javax.swing.JLabel l_9;
    private javax.swing.JLabel l_background;
    private javax.swing.JLabel l_console;
    private javax.swing.JLabel l_r1;
    private javax.swing.JLabel l_r2;
    private javax.swing.JLabel l_r3;
    private javax.swing.JLabel l_r4;
    private javax.swing.JLabel l_rules;
    private javax.swing.JLabel l_title;
    // End of variables declaration//GEN-END:variables

    Interface i;
    public void options() {
        i = new Interface();
        Interface._c_Frame(this);
        i.setIconFrame(this);
    }
}