/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import reference.Interface;
import reference.Numbersgen;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author LENOVO
 */
public class NumberGuessGame extends javax.swing.JFrame {

    /**
     * Creates new form GuessingGame
     */
    public NumberGuessGame() {
        initComponents();
        game();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        btn_quit = new javax.swing.JButton();
        l_guess = new javax.swing.JLabel();
        l_score = new javax.swing.JLabel();
        l_life = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        f_guess = new javax.swing.JTextField();
        btn_guess = new javax.swing.JButton();
        l_unshow = new javax.swing.JLabel();
        l_show = new javax.swing.JLabel();
        l_showRandom = new javax.swing.JLabel();
        btn_newRandom = new javax.swing.JButton();
        l_reset = new javax.swing.JLabel();
        l_bestscore = new javax.swing.JLabel();
        l_remarks = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("*********** NUMBER GUESSING GAME ***********");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 650, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 650, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        btn_menu.setBackground(new java.awt.Color(204, 255, 204));
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goback.png"))); // NOI18N
        btn_menu.setText("Back To Menu");
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menuMouseClicked(evt);
            }
        });
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 146, 40));

        btn_quit.setBackground(new java.awt.Color(204, 255, 204));
        btn_quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btn_quit.setText("Quit Game");
        btn_quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_quitMouseClicked(evt);
            }
        });
        btn_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, 40));

        l_guess.setBackground(new java.awt.Color(255, 255, 255));
        l_guess.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        l_guess.setForeground(new java.awt.Color(255, 255, 255));
        l_guess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_guess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guesses.png"))); // NOI18N
        l_guess.setText("Guesses: 0");
        l_guess.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(l_guess, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 112, 35));

        l_score.setBackground(new java.awt.Color(255, 255, 255));
        l_score.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        l_score.setForeground(new java.awt.Color(255, 255, 255));
        l_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_score.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/score.png"))); // NOI18N
        l_score.setText("Score: 0");
        l_score.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(l_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 112, 35));

        l_life.setBackground(new java.awt.Color(255, 255, 255));
        l_life.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        l_life.setForeground(new java.awt.Color(255, 255, 255));
        l_life.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_life.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/life.png"))); // NOI18N
        l_life.setText("Life: 10");
        l_life.setAutoscrolls(true);
        l_life.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(l_life, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 101, 35));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter Your Number (1-100):");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 284, -1));

        f_guess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f_guess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                f_guessKeyTyped(evt);
            }
        });
        jPanel1.add(f_guess, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 204, 44));

        btn_guess.setBackground(new java.awt.Color(153, 255, 153));
        btn_guess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkmark.png"))); // NOI18N
        btn_guess.setText("Guess");
        btn_guess.setToolTipText("Your Guess");
        btn_guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guessActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guess, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 129, 44));

        l_unshow.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        l_unshow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_unshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unshow.png"))); // NOI18N
        l_unshow.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        l_unshow.setMaximumSize(new java.awt.Dimension(50, 40));
        l_unshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_unshowMouseClicked(evt);
            }
        });
        jPanel1.add(l_unshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 49, 40));

        l_show.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        l_show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png"))); // NOI18N
        l_show.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        l_show.setMaximumSize(new java.awt.Dimension(50, 40));
        l_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_showMouseClicked(evt);
            }
        });
        jPanel1.add(l_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 49, 43));

        l_showRandom.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        l_showRandom.setForeground(new java.awt.Color(255, 255, 255));
        l_showRandom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_showRandom.setText("?");
        l_showRandom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(l_showRandom, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 49, 44));

        btn_newRandom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shuffle.png"))); // NOI18N
        btn_newRandom.setText("New RandomNumber");
        btn_newRandom.setToolTipText("Random Number");
        btn_newRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newRandomActionPerformed(evt);
            }
        });
        jPanel1.add(btn_newRandom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 219, 44));

        l_reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        l_reset.setToolTipText("Reset");
        l_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_resetMouseClicked(evt);
            }
        });
        jPanel1.add(l_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 35, 30));

        l_bestscore.setBackground(new java.awt.Color(204, 255, 204));
        l_bestscore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_bestscore.setText("Best Score: 0");
        l_bestscore.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        l_bestscore.setOpaque(true);
        jPanel1.add(l_bestscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 101, 33));

        l_remarks.setBackground(new java.awt.Color(255, 255, 255));
        l_remarks.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        l_remarks.setForeground(new java.awt.Color(255, 255, 255));
        l_remarks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_remarks.setText("***************** LETS SEE HOW FAST YOU CAN GUESS CORRECT *****************");
        l_remarks.setRequestFocusEnabled(false);
        jPanel1.add(l_remarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 650, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/game_background2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guessActionPerformed
        guess();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guessActionPerformed

    private void btn_newRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newRandomActionPerformed
        ran_newnumber();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_newRandomActionPerformed

    private void l_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_showMouseClicked
        l_show.setEnabled(false);   
        l_unshow.setEnabled(true);
        l_showRandom.setText(String.valueOf(random));// TODO add your handling code here:
    }//GEN-LAST:event_l_showMouseClicked

    private void l_unshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_unshowMouseClicked
        l_show.setEnabled(true);   
        l_unshow.setEnabled(false);
        l_showRandom.setText("?");        // TODO add your handling code here:
    }//GEN-LAST:event_l_unshowMouseClicked

    private void f_guessKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_guessKeyTyped
        Interface._int_Only(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_f_guessKeyTyped

    private void l_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_resetMouseClicked
        Object[] options = {"YES","NO"};
        int x = JOptionPane.showOptionDialog(this, "Are you sure, You want to Reset (yes/no) ?", "MESSAGE", 
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, null);  
        if (x == JOptionPane.YES_NO_OPTION){
            reset();
        }
    }//GEN-LAST:event_l_resetMouseClicked

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
            Menu mu = new Menu();
            mu.setVisible(true);  
            dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseClicked
            Menu mu = new Menu();
            mu.setVisible(true);  
            dispose();
    }//GEN-LAST:event_btn_menuMouseClicked

    private void btn_quitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quitMouseClicked
         Object [] options = {"YES","NO"};
        int x = JOptionPane.showOptionDialog(this, "Are you sure, You want to Quit (yes/no) ?", "MESSAGE", 
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, null);  
        if (x == JOptionPane.YES_NO_OPTION){
           System.exit(0); 
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btn_quitMouseClicked

    private void btn_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitActionPerformed
         Object[] options = {"YES","NO"};
        int x = JOptionPane.showOptionDialog(this, "Are you sure, You want to Quit (yes/no) ?", "MESSAGE", 
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, null);  
        if (x == JOptionPane.YES_NO_OPTION){
           System.exit(0); 
        }  
    }//GEN-LAST:event_btn_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberGuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberGuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberGuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberGuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberGuessGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guess;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_newRandom;
    private javax.swing.JButton btn_quit;
    private javax.swing.JTextField f_guess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_bestscore;
    private javax.swing.JLabel l_guess;
    private javax.swing.JLabel l_life;
    private javax.swing.JLabel l_remarks;
    private javax.swing.JLabel l_reset;
    private javax.swing.JLabel l_score;
    private javax.swing.JLabel l_show;
    private javax.swing.JLabel l_showRandom;
    private javax.swing.JLabel l_unshow;
    // End of variables declaration//GEN-END:variables

    Interface it;
    
    private int random = 0, bestScore = 0, currScore = 0;
    private byte guesses = 0, lives = 10, g_Error = 0, l_Error = 0;
    
    public void game(){
        it = new Interface();
        Interface._c_Frame(this);
        it.setIconFrame(this);
        random = Numbersgen._r_Number();
        l_unshow.setEnabled(false);
        bestScore = Interface.C_BestScore();
        l_bestscore.setText("Best Score: " + bestScore);
    }
    
    private void ran_newnumber() {
        random = Numbersgen._r_Number();
        
        f_guess.setText("");
        f_guess.requestFocus();
        
        l_unshow.setEnabled(false);
        l_show.setEnabled(true);
        l_showRandom.setText("?");
    }
    
    private void guess() {
        
        if (f_guess.getText().equals("")) {
            Interface._msg("Please Enter Your Number: ", 0);
            f_guess.requestFocus();
        }else if (Integer.parseInt(f_guess.getText()) >= 101 || Integer.parseInt(f_guess.getText()) < 1) {
            Interface._msg("Please Enter Your Number from 1-100: ", 0);
            f_guess.setText("");
            f_guess.requestFocus();
        } else {
            int io_Number = Integer.parseInt(f_guess.getText());
            
            if(io_Number == random) {
                Interface._msg("Hurray !! \nYOU WON !!!", 1);
                currScore++;
                l_score.setText("Score: " + currScore);
                update_B_Score();
               
                Object[] options = {"YES, I want to !!","NO, Exit Game!!"};
                int x = JOptionPane.showOptionDialog(this, "Do you want to Play Again ?", "MESSAGE", 
                        JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, null);  
                if (x == JOptionPane.YES_NO_OPTION){
                    newGame();
                } else {
                    System.exit(0);
                }
               
            }else {
                lives--;
                l_life.setText("Life: " + lives);
                
                if(lives <= 4) {
                    l_life.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/risk.png"))));
                }else {
                    l_life.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/life.png"))));
                }
                
                hint(random, io_Number);
                
                if(lives == 0) {
                    Interface._msg("You've used all your lives !! \nPlease try again !!", 0);
                    Object[] options = {"YES, I want to !!","NO, Exit Game !!"};
                int x = JOptionPane.showOptionDialog(this, "Do you want to Play Again ?", "MESSAGE", 
                        JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, null);  
                if (x == JOptionPane.YES_NO_OPTION){
                    newGame();
                } else {
                    System.exit(0);
                }
                }
            }
            guesses++;
            l_guess.setText("Guesses: " + guesses);
            l_guess.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/guesses.png"))));
        }
    }
    
    private void hint (int _ran_Num, int io_Number) {
        String mes;
        if(_ran_Num > io_Number){
            l_Error++;
            mes = msgHint(l_Error, (byte)1, io_Number);
            l_remarks.setText(mes);
        }else {
            g_Error++;
            mes = msgHint(g_Error, (byte)0, io_Number);
            l_remarks.setText(mes);
        }
    }
    
    private String msgHint(byte errorCount, byte errorCatcher, int numGuess) {
        String msg;
        switch(errorCatcher) {
            case 1:
                String msgfui[] = {String.valueOf(numGuess) + " is Lower than the random number ! U can do it !",
                String.valueOf(numGuess) + " is Lower than the random number ! Don't Give Up !",
                String.valueOf(numGuess) + " is Lower than the random number ! Oh!! Come ON!!",
                String.valueOf(numGuess) + " is Lower than the random number ! Im Tired of Giving Hints !" };
                if(errorCount < 2) {
                    msg = String.valueOf(numGuess) + " is Lower than the random number !";
                }else {
                    int randomMes = (int) Math.round(Math.random() * 3);
                    msg = msgfui[randomMes];
                }
                break;
            default:
                String msgfui1[] = {String.valueOf(numGuess) + " is Higher than the random number ! U can do it !",
                String.valueOf(numGuess) + " is Higher than the random number ! Don't Give Up !",
                String.valueOf(numGuess) + " is Higher than the random number ! Oh!! Come ON!!",
                String.valueOf(numGuess) + " is Higher than the random number ! Im Tired of Giving Hints !" };
                if(errorCount < 2) {
                    msg = String.valueOf(numGuess) + " is Higher than the random number !";
                }else {
                    int randomMes = (int) Math.round(Math.random() * 3);
                    msg = msgfui1[randomMes];
                }
                break;
        }
        return msg;
    }
    
    private void update_B_Score() {
        if(currScore > bestScore) {
            Interface._msg("Congratulations !! \n New Best Score !!", 1);
            Interface.setNewBestScore("bestScore[" + currScore + "]");
            bestScore = currScore;
            l_bestscore.setText("Best Score: " + bestScore);
        }
    }
    
    private void newGame() {
        f_guess.setText("");
        f_guess.requestFocus();
        
        l_remarks.setText("***************** LETS SEE HOW FAST YOU CAN GUESS CORRECT *****************");
        l_unshow.setEnabled(false);
        l_show.setEnabled(true);
        l_showRandom.setText("?");
        l_guess.setText("Guesses: 0");
        guesses = 0;
        
        l_life.setText("Life: 10");
        l_life.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/life.png"))));
        lives = 10;
        
        g_Error = 0;
        l_Error = 0;
        
        random = Numbersgen._r_Number();
    }
    
    private void reset() {
        f_guess.setText("");
        f_guess.requestFocus();
        
        l_remarks.setText("***************** LETS SEE HOW FAST YOU CAN GUESS CORRECT *****************");
        l_unshow.setEnabled(false);
        l_show.setEnabled(true);
        l_showRandom.setText("?");
        l_guess.setText("Guesses: 0");
        guesses = 0;
        
        l_life.setText("Life: 10");
        lives = 10;
        l_life.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/life.png"))));
        
        g_Error = 0;
        l_Error = 0;
        
        random = Numbersgen._r_Number();
        
        l_score.setText("Score: 0");
        currScore = 0;
        bestScore = 0;
        Interface.setNewBestScore("bestScore[" + bestScore + "]");
        l_bestscore.setText("Best Score: 0");
    }
}